### ISSUE TITLE
CLIENT ID

### ISSUE THREAD

**Issue by gamblor999** [matthuisman/kayo-for-channels#1]
Hi Matt,

Firstly awesome work you do here!  I thought i would throw my hat at trying to get flash news going,  (it will require small changes from your code from binge or kayo i said to myself thinking its also using streammotion......)

What exactly does the CLIENT ID do on your scripts when logging into stream motion  ( i am assuming this is unique per service eg Binge different to Kayo which is different to FlashNews   ?  where do you source it from ?

Thanks for any advice.

**Comment by matthuisman** [comment]
pretty sure thats what identities which service it is to streammotion.
if i recall, i couldn't find the clientid for flash due to no android-tv app.
