### ISSUE TITLE
Other sources ?

### ISSUE THREAD

**Issue by Ghawken** [matthuisman/kayo-for-channels#2]
Hi Matt,

Thanks for this - awesome work - and functions really well!

Any thoughts as to adding other sources - similar to what you have for Slyguy?

Particularly interested in Stan/Stan Sports?  As M3u

But regardless, thanks & well done!

**Comment by matthuisman** [comment]
Pretty sure nearly all the others use widevine encryption which ffmpeg / channels can't play sorry
